name: Setup the Python Environment

description: "Construct a Python environment for ci/cd using poetry"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Why is this not automatically happen?
        python-version: ${{ inputs.python-version || '3.10' }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
       # It's easier to cache if a virtual environment within the project is used
       virtualenvs-create: true
       virtualenvs-in-project: true
       installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install project
      shell: bash
      run: |
        # upgrade pip
        poetry run pip install --upgrade pip
        poetry install --no-interaction --all-extras

    - name: Documentation
      shell: bash
      run: |
        mkdir -p artifacts/build
        poetry show --only main --tree > artifacts/build/show.txt

    - name: Archive Documentation
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: artifacts/build
        retention-days: 1
