#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Setup the Python Environment

description: "Construct a Python environment for ci/cd using poetry"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.11'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # Why is this not automatically happen?
        python-version: ${{ inputs.python-version || '3.11' }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
       # It's easier to cache if a virtual environment within the project is used
       virtualenvs-create: true
       virtualenvs-in-project: true
       installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install project
      shell: bash
      run: |
        # upgrade pip
        poetry run pip install --upgrade pip
        poetry install --no-interaction --all-extras

    - name: Documentation
      shell: bash
      run: |
        mkdir -p artifacts/build
        poetry show --only main --tree > artifacts/build/show.txt

    # - name: Archive Documentation
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: build-${{ runner.os }}-${{ inputs.python-version }}
    #    path: artifacts/build
    #    retention-days: 1
