repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.286'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
        args: [ "--ignore", "book/**/*.md", "--ignore", "contributing/*.md" ]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-dependabot
        args: [ "--verbose" ]

      - id: check-github-actions
        args: ["--verbose"]

      - id: check-github-workflows
        args: ["--verbose"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
        - id: insert-license
          files: ^(actions)
          args:
            ['--license-filepath', 'copyright.txt', '--no-extra-eol']
