name: Compile a LaTeX document

description: "Compile a LaTeX document and upload it"

on:
  workflow_call:
    inputs:
      paper:
        description: 'paper'
        type: string
        required: true
      
      GITHUB_TOKEN:
        required: true

runs:
  using: "composite"
  steps:
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      
      - uses: wtfjoke/setup-tectonic@v2.1.0
        with:
          github-token: ${{ inputs.GITHUB_TOKEN }}
          biber-version: '2.17'
      
      - name: Run Tectonic
        shell: bash
        env:
          # as recommended by the problems in 
          # https://github.com/cvxgrp/robust_erm_note/actions/runs/5250958945/jobs/9485425629#step:5:1
          RUST_BACKTRACE: '1'
        run: |
          mkdir -p publish
          echo "Compiling ${{ inputs.paper }}"
          for f in ${{ inputs.paper }}
          do
            echo "-- Compiling $f"
            tectonic $f --outdir publish
          done

          
      # Push the paper folder to the draft branch
      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: draft # The branch the action should deploy to.
          folder: publish  # The folder the action should deploy.

      # To make your draft folder public you would have to go to Settings => Pages
