#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Build sphinx documentation

description: "Build sphinx documentation"

on:
  workflow_call:
    inputs:
      sphinx-folder:
        description: 'Sphinx folder'
        type: string
        required: false
        default: 'book/sphinx'

runs:
  using: "composite"

  steps:
      - uses: cvxgrp/.github/actions/uv/setup@main

      - name: Install sphinx
        shell: bash
        run: |
          uv pip install --no-cache-dir \
                     sphinx==7.2.6 \
                     sphinx-autoapi \
                     sphinx-rtd-theme

      - name: Build sphinx
        shell: bash
        run: |
          uv run sphinx-build -b html ${{ inputs.sphinx-folder || 'book/sphinx' }} artifacts/sphinx

      - name: Archive sphinx documentation
        uses: actions/upload-artifact@v4
        with:
          name: sphinx
          path: artifacts/sphinx
          retention-days: 1
