version: '3'

tasks:
    install:
        desc: "Install a Python virtual environment complete will all extras"
        cmds:
            - poetry install -vv --all-extras

    fmt:
        desc: "Run autoformatting and linting"
        cmds:
            - poetry run pip install pre-commit
            - poetry run pre-commit install
            - poetry run pre-commit run --all-files

    clean:
        desc: "Clean up caches and build artifacts"
        cmds:
            - git clean -X -d -f
            # remove all local branches that are 'gone'
            - git branch -v | grep "\[gone\]" | cut -f 3 -d ' ' | xargs git branch -D
