version: '3'
tasks:
    install:
        desc: "Install a virtual environment"
        cmds:
            - curl -LsSf https://astral.sh/uv/install.sh | sh
            - uv sync -vv --frozen

    fmt:
        desc: "Run autoformatting and linting"
        cmds:
            - task: install
            - uv pip install pre-commit
            - uv run pre-commit install
            - uv run pre-commit run --all-files

    test:
        desc: "Run the tests"
        cmds:
            - task: install
            - uv run pytest


    clean:
        desc: "Clean up caches and build artifacts"
        cmds:
            - git clean -X -d -f

    coverage:
        desc: "test with coverage"
        vars:
            PACKAGE_PATH: '{{.PACKAGE_PATH| default "cvx"}}'
        cmds:
            - task: install
            - uv pip install pytest pytest-cov
            - uv run coverage run --source={{.PACKAGE_PATH}}/. -m pytest
            - uv run coverage report -m
            - uv run coverage html
            - cmd: open htmlcov/index.html
              platforms: [darwin]
            - cmd: xdg-open htmlcov/index.html 2> /dev/null
              platforms: [linux]

    marimo:
        desc: "Install marimo"
        vars:
            MARIMO_PATH: '{{.MARIMO_PATH| default "book/marimo"}}'
        cmds:
            - task: install
            #- uv pip install marimo
            - uvx marimo edit {{.MARIMO_PATH}}
