version: '3'


tasks:
    test:
        desc: "Run tests"
        cmds:
            - poetry install -vv --all-extras
            - poetry run pip install pytest
            - poetry run pytest

    coverage:
        desc: "test with coverage"
        cmds:
            - poetry install -vv --all-extras
            - poetry run pip install pytest pytest-cov
            - poetry run coverage run --source=adia/. -m pytest
            - poetry run coverage report -m
            - poetry run coverage html
            - cmd: open htmlcov/index.html
              platforms: [darwin]
            - cmd: xdg-open htmlcov/index.html 2> /dev/null
              platforms: [linux]
