# .github/workflows/python-release.yml
name: Release Python Package

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'
      build-tool:
        required: false
        type: string
        default: 'hatch'
    secrets:
      PYPI_TOKEN:
        required: false  # Not needed with trusted publishing

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

  build:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install build tool
        run: |
          pip install ${{ inputs.build-tool }}

      - name: Build package
        run: |
          sed -i "s/0.0.0/${{ needs.tag.outputs.tag }}/" pyproject.toml
          ${{ inputs.build-tool }} build

      # Important: Set correct ownership for Docker usage
      - name: Fix ownership
        run: |
          sudo chown -R $(id -u):$(id -g) dist/

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # The PyPI publish action needs to run in the container context
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
