# .github/actions/release/action.yml
name: 'Python Release Action'
description: 'Bumps version, builds and publishes Python package to PyPI'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  build-tool:
    description: 'Build tool to use (hatch, poetry, etc)'
    required: false
    default: 'hatch'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ github.token }}

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build tool
      shell: bash
      run: pip install ${{ inputs.build-tool }}

    - name: Build package
      shell: bash
      run: |
        sed -i "s/0.0.0/${{ steps.tag_version.outputs.new_tag }}/" pyproject.toml
        ${{ inputs.build-tool }} build

    - name: Fix ownership
      shell: bash
      run: sudo chown -R $(id -u):$(id -g) dist/

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
