#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Release

description: "Release with poetry"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'

runs:
  using: "composite"

  steps:
    - uses: cvxgrp/.github/actions/setup-environment@main
      with:
        python-version: "${{ inputs.python-version || '3.10' }}"

    - name: Change version in pyproject.toml
      shell: bash
      run: |
         poetry version ${{  github.ref_name }}
         poetry build

    - name: Mint token
      id: mint
      uses: tschm/token-mint-action@v1.0.3

    - name: Publish the package with poetry
      shell: bash
      run: |
         poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
