#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Publish Python Package
description: "Publish dist"

permissions:
  # This permission is required for trusted publishing.
  id-token: write

inputs:
  url:
    description: 'url of pypi'
    required: true
  python-version:
    description: 'Python version to use for building'
    type: string
    required: false
    default: '3.12'

runs:
  using: "composite"

  steps:
    # Download the dist folder from the build job
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${inputs.url}
