name: Publish Python Package
description: "Publish dist"


runs:
  using: "composite"

  steps:
    - uses: actions/setup-python@v3

    # Download the dist folder from the build job
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    # Generate the token
    - name: Mint token
      id: mint
      uses: tschm/token-mint-action@v1.0.2

    # Install twine and upload the dist folder using the token
    - name: Publish the package
      shell: bash
      run: |
         pip install twine
         twine upload --verbose -u __token__ -p '${{ steps.mint.outputs.api-token }}' dist/*
