name: Build the Jupyter Book

description: "Build jupyter book"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'
      kernel:
        description: 'Jupyter kernel'
        type: string
        required: false
        default: 'cvx'
        
runs:
    using: "composite"

    steps:
      #- name: Check out repository
      #  uses: actions/checkout@v3

      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          python-version: ${{ inputs.python-version || '3.10' }}
          
      - name: Install jupyterbook
        shell: bash
        run: |
          poetry run pip install jupyter-book
          # There is no need to create the kernel if the jupyter book is installed within the same virtual environment as the package
          # poetry run python -m ipykernel install --user --name=${{ inputs.kernel || 'cvx' }}

      - uses: actions/cache@v3
        name: Jupyter Cache
        with:
          path: ~/book/_build/.jupyter_cache
          key: ${{ runner.os }}-jupyter-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-jupyter-
            
      # Build the book
      - name: Build the book
        shell: bash
        run: |
          poetry run jupyter-book clean book
          poetry run jupyter-book build book
          # Create this weird .nojekyll file
          # see https://jupyterbook.org/en/stable/publish/gh-pages.html#option-1-copy-and-paste-your-books-build-contents-into-a-new-folder
          touch book/_build/html/.nojekyll
          
      # Upload the book
      - name: Archive book
        uses: actions/upload-artifact@v3
        with:
          name: book
          path: book/_build/html/
          retention-days: 1
