#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Build the Jupyter Book

description: "Build jupyter book"

inputs:
  python-version:
    description: 'Python version'
    type: string
    required: false
    default: '3.12'

  kernel:
    description: 'Jupyter kernel'
    type: string
    required: false
    default: 'cvx'
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: '.'


runs:
    using: "composite"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          # It's easier to cache if a virtual environment within the project is used
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install project
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          # upgrade pip
          poetry run pip install --upgrade pip
          poetry install --no-interaction --all-extras

      - name: Install jupyterbook
        shell: bash
        run: |
          poetry run pip install jupyter-book
          # There is no need to create the kernel if the jupyter book is installed within the same virtual environment as the package
          # poetry run python -m ipykernel install --user --name=${{ inputs.kernel || 'cvx' }}

      - uses: actions/cache@v4
        name: Jupyter Cache
        with:
          path: ~/book/_build/.jupyter_cache
          key: ${{ runner.os }}-jupyter-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-jupyter-

      # Build the book
      - name: Build the book
        shell: bash
        run: |
          poetry run jupyter-book clean book
          poetry run jupyter-book build book
          # Create this weird .nojekyll file
          # We do this in the book action... This is the wrong place
          # see https://jupyterbook.org/en/stable/publish/gh-pages.html#option-1-copy-and-paste-your-books-build-contents-into-a-new-folder
          # touch book/_build/html/.nojekyll

      # Upload the book
      - name: Archive book
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: ${{ inputs.working-directory }}/book/_build/html/
          retention-days: 1
