name: Analyse Dependencies

description: "Construct dependency tree"

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        type: string
        required: true
      python-version:
        description: 'Python version'
        type: string
        required: true
      source-folder:
        description: 'Source folder'
        type: string
        required: true

runs:
    using: "composite"
    steps:

      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          os: ${{ runner.os }}
          python-version: "${{ inputs.python-version }}"

      - name: Export dependencies
        shell: bash
        run: |
          poetry show --only main --tree
          mkdir -p artifacts/build
          poetry show --only main --tree > artifacts/build/show.txt

      - name: Archive dependencies
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: artifacts/build
    
