name: Analyse Dependencies

description: "Construct dependency tree"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'

runs:
    using: "composite"
    steps:

      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          python-version: "${{ inputs.python-version || '3.10' }}"

      - name: Export dependencies
        shell: bash
        run: |
          poetry show --only main --tree
          mkdir -p artifacts/build
          poetry show --only main --tree > artifacts/build/show.txt

      - name: Archive dependencies
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: artifacts/build
          retention-days: 1    
