name: Analyse use of docstrings

description: "Analyse docstrings"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'
      source-folder:
        description: 'Source folder'
        type: string
        required: false
        default: 'cvx'

runs:
  using: "composite"
  steps:
      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          python-version: ${{ inputs.python-version || '3.10' }}

      - name: Install pytest
        shell: bash
        run: |
            poetry run pip install --no-cache-dir \
                       docstr-coverage

      - name: Run tests
        shell: bash
        run : |
          docstr-coverage ${{ inputs.source-folder || 'cvx' }}
