name: Build sphinx documentation

description: "Build sphinx documentation"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'
      sphinx-folder:
        description: 'Sphinx folder'
        type: string
        required: false
        default: 'book/sphinx'

runs:
  using: "composite"
  steps:
      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          os: ${{ runner.os }}
          python-version: ${{ inputs.python-version :-'3.10' }}
          
      - name: Install sphinx
        shell: bash
        run: |
          poetry run pip install --no-cache-dir \
                     sphinx==5.0.2 \
                     sphinx-autoapi==1.8.4 \
                     sphinx-rtd-theme==1.0.0 \
                     recommonmark==0.7.1

      - name: Build sphinx
        shell: bash
        run: |
          mkdir -p artifacts/sphinx
          SPHINX_FOLDER=${{ inputs.sphinx-folder:-'book/sphinx' }}
          echo $SPHINX_FOLDER
          poetry run sphinx-build -b html $SPHINX_FOLDER artifacts/sphinx

      - name: Archive sphinx documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx
          path: artifacts/sphinx
          retention-days: 1
          
