name: Count lines

description: "count lines"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        required: false
        default: '3.10'
      source-folder:
        description: 'Source folder'
        type: string
        required: false
        default: 'cvx'

runs:
    using: "composite"
    steps:

      - uses: cvxgrp/.github/actions/setup-environment@main
        with:
          python-version: "${{ inputs.python-version || '3.10' }}"

      - name: count
        shell: bash
        run: |
            pip install pygount==1.5.1
            mkdir -p artifacts/lines
            pygount --format=summary --out=artifacts/lines/lines.txt ${{ inputs.source-folder || 'cvx' }}

      - name: Archive counts
        uses: actions/upload-artifact@v3
        with:
          name: count
          path: artifacts/lines
          retention-days: 1
