name: "book"

on:
- push


jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/sphinx@v2.1.1

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/test@v2.1.1

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/pdoc@v2.1.1

  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/marimo@v2.1.1

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter, pdoc, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.1.1
