name: "book"

# This workflow builds and publishes documentation for the repository
# It runs automatically on every push to the repository
# The workflow includes multiple documentation generation jobs and combines them into a final book

on:
- push


jobs:
  # Runs tests and generates coverage reports
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/coverage@v2.2.8
        with:
          source-folder: 'src/cvx'
          tests-folder: 'src/tests'

  # Generates API documentation using pdoc
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/pdoc@v2.2.8
        with:
          source-folder: 'src/cvx'

  # Generates interactive Marimo notebooks for documentation
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/marimo@v2.2.8
        with:
          source-folder: 'book/marimo'

  # Processes Jupyter notebooks for documentation
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/jupyter@v2.2.8

  # Combines all documentation outputs into a final book
  # This job only runs after all other jobs have completed successfully
  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, pdoc, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.8
