name: "book"

on:
- push


jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/sphinx@main

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/test@main

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/pdoc@main

  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/marimo@main

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter, pdoc, marimo]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/book@main
