name: "book"

on:
- push


jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.2

      - uses: cvxgrp/.github/actions/sphinx@v2.2.2
        with:
          source-folder: 'src/cvx'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.2

      - uses: cvxgrp/.github/actions/coverage@v2.2.2
        with:
          source-folder: 'src/cvx'
          tests-folder: 'src/tests'

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.2

      - uses: cvxgrp/.github/actions/pdoc@v2.2.2
        with:
          source-folder: 'src/cvx'

  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.2

      - uses: cvxgrp/.github/actions/marimo@v2.2.2
        with:
          source-folder: 'book/marimo'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.2

      - uses: cvxgrp/.github/actions/jupyter@v2.2.2

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter, pdoc, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.2
