name: Build LaTeX document

# This workflow compiles LaTeX documents in the repository
# It runs automatically on every push to the repository
# The workflow builds the specified LaTeX file and can optionally create releases

on:
  push

jobs:
  # Builds the LaTeX paper specified in the workflow configuration
  # Requires write permissions to publish the compiled document
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v5

      - uses: cvxgrp/.github/actions/latex@main
        with:
          # IMPORTANT: point to the correct file
          paper: paper.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          create-release: 'true'
