name: 'Core Setup'
description: 'Sets up Python and uv with dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: '.'

runs:
    using: "composite"
    steps:
      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a

      - name: Set up Python and install dependencies
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          uv python install ${{ inputs.python-version }}
          uv venv
          uv pip install --no-cache-dir  -r requirements.txt
