name: "Bump version and create release"
description: "Bumps version, creates a tag, and publishes a release."
author: "Your Name"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true

outputs:
  tag:
    description: "The new tag created by the action"

runs:
  using: "composite"
  steps:
    - name: Bump version and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github_token }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true

    - name: Set output
      run: echo "tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV
