name: "Bump version and create release"
description: "Bumps version, creates a tag, and publishes a release."
author: "Your Name"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Bump version and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github_token }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install hatch
      shell: bash
      run: |
        pip install hatch

    - name: Set output
      shell: bash
      run: echo "tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

    - name: Build package
      shell: bash
      run: |
        echo "Environment ${{ env.tag }}"
        sed -i "s/0.0.0/${{ env.tag }}/" pyproject.toml
        # Constructs the dist folder
        hatch build

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
