name: "Bump version and create release"
description: "Bumps version, creates a tag, and publishes a release."

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  python_version:
    description: 'Python version to use for the build'
    required: false
    default: '3.12'
  build_package:
    description: 'Whether to build and include package artifacts in the release'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # -----------------------------------------------------------------------------
    # Step 1: Checkout the repository
    # -----------------------------------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # -----------------------------------------------------------------------------
    # Step 2: Bump version and tag
    # -----------------------------------------------------------------------------
    - name: Bump version and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github_token }}

    # -----------------------------------------------------------------------------
    # Step 3: Set up Python environment
    # -----------------------------------------------------------------------------
    - name: Set up Python ${{ inputs.python_version }}
      if: inputs.build_package == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'  # Enable caching for pip dependencies

    # -----------------------------------------------------------------------------
    # Step 4: Install dependencies (hatch for packaging)
    # -----------------------------------------------------------------------------
    - name: Install dependencies
      if: inputs.build_package == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip hatch

    # -----------------------------------------------------------------------------
    # Step 5: Update version in pyproject.toml
    # -----------------------------------------------------------------------------
    - name: Update version in pyproject.toml
      if: inputs.build_package == 'true'
      shell: bash
      run: |
        echo "Updating version to ${{ steps.tag_version.outputs.new_tag }}"
        sed -i "s/0.0.0/${{ steps.tag_version.outputs.new_tag }}/" pyproject.toml

    # -----------------------------------------------------------------------------
    # Step 6: Build the package
    # -----------------------------------------------------------------------------
    - name: Build package
      if: inputs.build_package == 'true'
      shell: bash
      run: |
        echo "Building package for version: ${{ steps.tag_version.outputs.new_tag }}"
        hatch build

    # -----------------------------------------------------------------------------
    # Step 7: Upload build artifacts
    # -----------------------------------------------------------------------------
    - name: Upload distribution artifacts
      if: inputs.build_package == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1

    # -----------------------------------------------------------------------------
    # Step 8: Create GitHub release
    # -----------------------------------------------------------------------------
    - name: Create GitHub release with artifacts
      if: inputs.build_package == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
        files: dist/*

    - name: Create GitHub release without artifacts
      if: inputs.build_package != 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        generate_release_notes: true
