name: BOOK

# This workflow builds and publishes documentation for the repository
# It runs automatically on every push to the repository
# The workflow includes multiple documentation generation jobs and combines them into a final book

on:
  push:

jobs:
    # Generates interactive Marimo notebooks for documentation
    marimo:
      runs-on: "ubuntu-latest"

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/marimo

    # Generates API documentation using pdoc
    pdoc:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/pdoc

    # Checks the age of the repository and its files
    age:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/age

    # Builds Sphinx documentation from the specified folder
    sphinx:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/sphinx
          with:
            sphinx-folder: 'book/sphinx'

    # Runs tests and generates coverage reports
    test:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/coverage
          with:
            coveralls: 'false'
            tests-folder: 'src/tests'

    # Processes Jupyter notebooks for documentation
    jupyter:
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/environment

        - uses: ./actions/jupyter

    # Combines all documentation outputs into a final book
    # This job only runs after all other jobs have completed successfully
    book:
      runs-on: "ubuntu-latest"
      needs: [test, pdoc, sphinx, jupyter, marimo, age]

      permissions:
        contents: write

      steps:
        - name: Checkout [${{ github.repository }}]
          uses: actions/checkout@v4

        - uses: ./actions/book
