name: "Build book"

on:
  push
    #:
    #branches:
    #  - main


jobs:
  #runs-on: ubuntu-latest

  #  steps:
  #sphinx:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/sphinx@main
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      #- uses: actions/checkout@v4
      - uses: ./actions/pdoc

  test:
    runs-on: "ubuntu-latest"
    steps:
      #- uses: actions/checkout@v4
      - uses: ./actions/coverage

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      #- uses: actions/checkout@v4
      - uses: ./actions/jupyter

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      #- uses: actions/checkout@v4
      - uses: ./actions/book
