name: "book"

on:
  push:
    branches:
      - main


jobs:
  #sphinx:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/sphinx@main
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/pdoc

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/coverage

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/jupyter

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - uses: ./actions/book
