name: "book"

on:
- push

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/uv/marimo@main

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/uv/pdoc@main

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/uv/coverage@main

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/uv/jupyter@main

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - uses: ./actions/book@main
