name: "book"

on:
- push

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/uv/marimo
        with:
          working-directory: .github/hello-world

  #sphinx:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/sphinx@main

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/uv/pdoc
        with:
          working-directory: .github/hello-world

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/uv/coverage
        with:
          working-directory: .github/hello-world

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./actions/uv/jupyter
        with:
          working-directory: .github/hello-world

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - uses: ./actions/book@main
