name: Upload Python Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: ./actions/build
        with:
          working-directory: '.github/hello-world'
