name: CI

# This workflow runs continuous integration tests across multiple platforms and Python versions
# It runs automatically on every push to the repository
# The workflow ensures the code works consistently across different environments

on:
  push:

jobs:

  # Tests the code on multiple operating systems and Python versions
  # The job must pass on all combinations to ensure cross-platform compatibility
  pass:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ '3.10', '3.11', '3.12', '3.13']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v5

      - uses: ./actions/environment
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Test a project
        uses: ./actions/test
        with:
          tests-folder: 'src/tests'
