name: CI

on:
  push:

jobs:

  pass:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    # https://github.com/glassechidna/ghaoidc/issues/1
    #permissions:
    #  id-token: write
    #  contents: read

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Init a project
        shell: bash
        run: |
          - uv init

      - name: Setup an environment
        id: setup
        uses: ./actions/uv/setup
