name: coverage

on:
  [push]

jobs:
  run-deptry:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./actions/coverage
        with:
          source-folder: "cvx"

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          files: artifacts/tests/coverage/coverage.info
          format: lcov
