name: Analyse with deptry

on:
  [push]

jobs:
  run-coverage-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./actions/deptry
        with:
          source-folder: "cvx"
