name: LATEX

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX document
        uses: ./actions/latex
        with:
          paper: ".github/hello-paper/main.tex"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          create-release: 'true'

      #- name: Upload build artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: latex-build-${{ github.sha }}
      #    path: publish/
      #    retention-days: 7
