name: Lint README

on:
  push

jobs:
  lint-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install markdown-lint
      run: npm install -g markdown-lint

    - name: Lint README
      run: markdown-lint README.md
