name: pre-commit

# This workflow runs code quality checks and dependency analysis
# It runs automatically on every push to the repository
# The workflow ensures code meets quality standards and has no dependency issues

on:
  push:

jobs:
  # Analyzes project dependencies to detect unused or missing dependencies
  # Uses deptry tool to scan the specified source folder
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: ./actions/environment

      - uses: ./actions/deptry
        with:
          source-folder: 'src/cvx'

  # Runs pre-commit hooks on all files in the repository
  # Checks code formatting, linting, and other quality checks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
