name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout [${{ github.repository }}]
      #  uses: actions/checkout@v4

      - uses: ./actions/uv/deptry
        with:
          working-directory: '.github/hello-world'
