name: Build LaTeX document

on:
  [push]

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./actions/latex
        with:
          paper: tests/tex/*.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-folder: /tests/texgroup

      - uses: ./actions/latex
        with:
          paper: tests/tex/Hydra.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
