name: Build pdoc documentation

on:
  [push]

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      #- name: Set up Git repository
      #  uses: actions/checkout@v4

      - uses: ./actions/pdoc
        with:
          source-folder: "cvx"
